version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/services/tasks"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: lockfile-only

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"