sonar.projectKey=Training-for-studies-Master_refonte-todolist
sonar.organization=training-for-studies-master

sonar.host.url=https://sonarcloud.io

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts,**/*.test.js